Configure ADF to checkpoint incoming bundles
CDCgov/phdi-azure pull request #187
Opened 2023-06-28 20:34 UTC by bamader

This PR allows the pipeline to capture pre- and post-standardization snapshots of the FHIR bundles it processes. This will allow us to do downstream analysis on the impact of our various standardization functions.

While I'm confident in the ADF JSON config file being right, I am _not_ confident in the correct way of accessing the phi storage container's URL from within the synapse notebook (I believe we need to do the snapshot modifying there as well to make before and after versions of the data LAC sends us). Dan, I pulled that (what I think is an) environment variable out of `main.tf` because I saw it as a shared variable in `outputs.tf`. That might be totally wrong though.

2023-06-29 12:48 UTC, DanPaseltiner requested changes
This is looking really great. A couple things I think we should tweak before merging.

1. As discussed lets reorder the pipeline config to make it a little easier to read
2. See my comment below on the `bundle-diffs` container

2023-06-29 12:48 UTC, DanPaseltiner commented on scripts/Synapse/convertParquetMPI.ipynb
> +        "            'bucket_name': 'bundle-diffs',\n",
Two thoughts here:

1. This container doesn't currently exist and this service isn't smart enough to create it for us, so well need to add terraform coverage for this. [Here](https://github.com/CDCgov/phdi-azure/blob/main/terraform/modules/shared/main.tf#L22) is an example of where we do this for the `source-data` container.
2. We aren't really storing the diffs so personally I don't think "bundle-diffs" is a good name. What about "bundle-snapshots"?

2023-06-29 21:52 UTC, bamader commented
All comments addressed and the branch passed a successful deploy

2023-06-30 13:23 UTC, DanPaseltiner approved these changes
This all looks good to me. Thanks for the conversation yesterday AM and making these minor changes. Since you are out today I'm going to go ahead and merge this, as we discussed.

2023-06-30 13:23 UTC, DanPaseltiner commented on terraform/modules/shared/main.tf
🚀

2023-06-30 13:23 UTC, merged