Add example api calls to impl guide by George and Gordon
CDCgov/phdi-azure pull request #45
Opened 2023-01-27 19:42 UTC by gordonfarrell

Adds a section to the bottom of the Impl guide giving several examples of inserting, modifying and retrieving data from the FHIR server

2023-01-27 19:57 UTC, DanPaseltiner requested changes
Thank you for putting this together. Looks great! I have two thoughts:

1. Could we export the Postman collection to JSON and include that file along with instructions for loading it into Postman so that users can get up and running with these requests quickly?
2. I'm starting to wonder if we are beginning to overload the IG and getting started docs. What are your thoughts on moving this new content to a separate doc and linking to it from the IG?

2023-01-27 19:57 UTC, DanPaseltiner commented on docs/implementation-guide.md
> +
Can we mention the need to `az login` initially?

2023-01-27 19:57 UTC, DanPaseltiner commented on docs/implementation-guide.md
> +`$everything`
This cool. I didn't know about `$everything`!

2023-01-27 19:57 UTC, DanPaseltiner commented on docs/implementation-guide.md
> +`$everything`
We might want to include `_count` to set the page size.

2023-01-27 19:57 UTC, DanPaseltiner commented on docs/implementation-guide.md
> +Once you have data in your FHIR server you can access it through REST API calls. Below are SOME examples of calls you can make.
Could we provide links to the MSFT FHIR API docs and the Hl7 docs? "For more information checkout out these resources."

2023-01-31 13:34 UTC, georgehager commented on docs/implementation-guide.md
> +    GET a specific Patient by id:
@gordonfarrell When you push up changes for this, can you bump this template out, and put it above line 191? I think it makes more sense to organize it that way.

2023-01-31 14:21 UTC, georgehager commented
@DanPaseltiner Yep, we can put together a Postman collection! I'm assuming we'll want to set it up with some variables that whoever's using it can easily replace based on their fhir server values. Then the requests should just work out of the 🥡

2023-01-31 14:44 UTC, DanPaseltiner commented
@georgehager, yes that's exactly what I'm thinking! Off-hand we'll need variables for:

1. FHIR server URL
2. Bearer token

2023-01-31 16:08 UTC, georgehager commented
> @georgehager, yes that's exactly what I'm thinking! Off-hand we'll need variables for:
> 
> 1. FHIR server URL
> 2. Bearer token

Great! Postman actually has a nice way to specify authorization separate from variables. I'm also adding placeholders for other variables like patient id, etc.

2023-01-31 20:50 UTC, georgehager commented on docs/phdi-fhir-api-template.postman_collection.json
> +				"value": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL3RhYnVsYXRpb25kZWJ1Zy1zZXJ2ZXIx
we should clear this out before merging

2023-01-31 20:51 UTC, georgehager commented on docs/phdi-fhir-api-template.postman_collection.json
> +			"value": "https://tabulationdebug-server1.fhir.azurehealthcareapis.com",
should probably also clear the values for all these variables too before merging, unless we're gonna have folks test with this fhir server specifically.

2023-02-01 13:47 UTC, georgehager commented on docs/phdi-fhir-api-template.postman_collection.json
> +			"key": "resource-id",
We can remove this one - it's not actually used for anything

2023-02-01 13:54 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +    - The end of Step 4 of this guide has a CURL example
We should paste the curl example directly or link to the other .md

2023-02-01 13:56 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +  - Add your generated authorization token to the Authorization tab and your FHIR server url to the variables tab.
Will also need to update all the id variables, reminder to add that here

2023-02-01 13:59 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +`_count=<desired number of items>`
should be `?_count=<blah blah>`

2023-02-01 16:23 UTC, DanPaseltiner approved these changes
After addressing @georgehager's comments LGTM. Thanks for putting this together. Still waiting to hear back from LAC about scheduling a demo call with them. Nice work!

2023-02-01 17:58 UTC, georgehager requested changes
Looks great! Just a couple comments for the .md file.

2023-02-01 17:58 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +    - The end of Step 4 of this guide has a CURL example
@gordonfarrell flagging this ^

2023-02-01 17:58 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +  - Add your generated authorization token to the Authorization tab and your FHIR server url to the variables tab.
Not sure if you saw this since it wasn't part of a review, flagging now @gordonfarrell

2023-02-01 17:58 UTC, georgehager commented on docs/basic-guide-to-fhir-api-calls.md
> +`_count=<desired number of items>`
same @gordonfarrell

2023-02-01 17:59 UTC, georgehager commented
@gordonfarrell For some reason my original comments aren't showing up under my review, but if you jump to the code in github you should see my original questions.

2023-02-02 13:40 UTC, georgehager approved these changes

2023-02-07 16:29 UTC, merged