Update ReadSourceData to extract RR fields --> Insert into eICR
CDCgov/phdi-azure pull request #55
Opened 2023-03-08 14:17 UTC by georgehager

2023-03-10 16:01 UTC, DanPaseltiner approved these changes
LGTM! Thanks for putting this together @georgehager. I'd like us to add a doc string to the `rr_to_ecr()` function, but don't feel it needs to be blocking.

2023-03-10 16:51 UTC, georgehager commented on serverless-functions/ReadSourceData/__init__.py
> +def rr_to_ecr(rr, ecr):
✅

2023-03-10 16:59 UTC, BradySkylight requested changes
We need to add one more field that is currently missing, from the RR into the eICR, the Status.  I missed this when we were doing some digging on how to find/pull the fields from the eICR that were required.

2023-03-10 18:22 UTC, georgehager commented
> We need to add one more field that is currently missing, from the RR into the eICR, the Status. I missed this when we were doing some digging on how to find/pull the fields from the eICR that were required.

Thanks for adding this @BradySkylight! Looks like you fixed the failing test issue - I can deploy and test in Azure if we want one more check before moving forward?

2023-03-10 19:07 UTC, BradySkylight approved these changes
Added some new code to handle the 'status' from RR.... as long as George and others are ok with this addition - I approve of all other sections.

2023-03-10 19:46 UTC, BradySkylight commented
> > We need to add one more field that is currently missing, from the RR into the eICR, the Status. I missed this when we were doing some digging on how to find/pull the fields from the eICR that were required.
> 
> Thanks for adding this @BradySkylight! Looks like you fixed the failing test issue - I can deploy and test in Azure if we want one more check before moving forward?

That would be nice if you could do that!

2023-03-13 19:37 UTC, georgehager commented
Final test in Azure succeeded so I'll go ahead and merge this now @DanPaseltiner @BradySkylight

2023-03-13 19:37 UTC, merged